/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Controls when the tracker runs.
 */
export type Trigger = {
  [k: string]: unknown;
} & {
  /**
   * If 'automatic', Journium runs this tracker on a schedule. If 'manual', it only runs when explicitly triggered.
   */
  mode: "automatic" | "manual";
  /**
   * Required when mode is 'automatic'. Either a preset cadence or a cron schedule.
   */
  schedule?:
    | ("hourly" | "daily" | "weekly" | "monthly")
    | {
        /**
         * Cron expression (format/validation is handled by Journium at runtime).
         */
        cron: string;
      };
};
/**
 * Controls when the tracker runs.
 */
export type Trigger1 = {
  [k: string]: unknown;
} & {
  /**
   * If 'automatic', Journium runs this tracker on a schedule. If 'manual', it only runs when explicitly triggered.
   */
  mode: "automatic" | "manual";
  /**
   * Required when mode is 'automatic'. Either a preset cadence or a cron schedule.
   */
  schedule?:
    | ("hourly" | "daily" | "weekly" | "monthly")
    | {
        /**
         * Cron expression (format/validation is handled by Journium at runtime).
         */
        cron: string;
      };
};

/**
 * Schema for defining a Journium InsightTracker resource (Analytics as Code).
 */
export interface JourniumInsightTracker {
  /**
   * API version of this resource. Must be 'journium.io/v0Alpha'.
   */
  apiVersion: "journium.io/v0Alpha";
  /**
   * Resource kind. Must be 'InsightTracker'.
   */
  kind: "InsightTracker";
  /**
   * Standard resource metadata (name, display name, labels, etc.).
   */
  metadata: {
    /**
     * Unique identifier for this tracker. Use kebab-case (e.g., 'signup-to-first-habit').
     */
    name: string;
    /**
     * Human-friendly name shown in the Journium UI (e.g., 'Signup to First Habit Dropoff').
     */
    displayName: string;
    /**
     * Description of the tracker. This is used to describe the tracker in the Journium UI.
     */
    description?: string;
  };
  /**
   * Tracker specification: defines how this insight tracker is evaluated and produced.
   */
  spec: LLMSpec | FunnelSpec;
}
/**
 * LLM-based insight tracker spec.
 */
export interface LLMSpec {
  /**
   * Spec type discriminator. Must be 'LLM'.
   */
  type: "LLM";
  trigger: Trigger;
  /**
   * LLM prompt used to generate the insight.
   */
  llmPrompt: string;
  data: DataSpec;
}
/**
 * Event data selection and limits.
 */
export interface DataSpec {
  /**
   * Optional minimum number of events required to run the tracker.
   */
  minEvents?: number;
  /**
   * Optional maximum number of events to consider. If omitted, the execution engine applies a reasonable default.
   */
  maxEvents?: number;
  /**
   * Events to include. Use '*' for all events, or provide an explicit allowlist of event names.
   */
  events?: "*" | [string, ...string[]];
}
/**
 * Funnel-based insight tracker spec.
 */
export interface FunnelSpec {
  /**
   * Spec type discriminator. Must be 'funnel'.
   */
  type: "funnel";
  trigger: Trigger1;
  data: DataSpec1;
}
/**
 * Event data selection and limits.
 */
export interface DataSpec1 {
  /**
   * Optional minimum number of events required to run the tracker.
   */
  minEvents?: number;
  /**
   * Optional maximum number of events to consider. If omitted, the execution engine applies a reasonable default.
   */
  maxEvents?: number;
  /**
   * Events to include. Use '*' for all events, or provide an explicit allowlist of event names.
   */
  events?: "*" | [string, ...string[]];
}
