# yaml-language-server: $schema=../../../schemas/journium-insight-tracker.v1.schema.json
apiVersion: journium.io/beta
kind: InsightTracker
metadata:
  name: signup-to-first-habit
  displayName: Signup to First Habit Dropoff
spec:
  type: funnel
  entity: person_id
  window:
    lookback: 7d

  steps:
    - id: signup
      match:
        event: signup_completed
    - id: habit_created
      match:
        event: habit_created

  output:
    card:
      title: "Users dropping before first habit"
      primaryMetric: dropoff_rate
